# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-02 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002__'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='allow_tokens',
            field=models.BooleanField(default=True, help_text=b'Allow user to ask tokens'),
        ),
    ]
