# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-10-17 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003__'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='allow_alerts',
            field=models.BooleanField(default=False, help_text=b'Allow user to create alerts'),
        ),
    ]
