# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-20 09:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home_logs.utils.unique


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sensor',
            name='uuid',
            field=models.CharField(default=home_logs.utils.unique.get, editable=False, max_length=50, unique=True),
        ),
    ]
