# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-10-17 14:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='creator',
            field=models.ForeignKey(help_text=b'The user who created the alert', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alert',
            name='max_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='min_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='sensor',
            field=models.ForeignKey(help_text=b'Sensor to monitor', on_delete=django.db.models.deletion.CASCADE, to='property.Sensor'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='space',
            field=models.ForeignKey(help_text=b'Space to monitor', on_delete=django.db.models.deletion.CASCADE, to='property.Space'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
