# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-10-17 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002__'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='title',
            field=models.CharField(default=b'', max_length=255),
        ),
    ]
