# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-05 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002__'),
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='space',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='property.Space'),
        ),
    ]
