# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-20 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003__'),
        ('logs', '0002_measurement_space'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='measurement',
            unique_together=set([('sensor', 'created_on')]),
        ),
    ]
