# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-14 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DavisMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('kind', models.CharField(max_length=50)),
                ('measured', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
