# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-07 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005__'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='davismeasurement',
            unique_together=set([('measured', 'kind')]),
        ),
    ]
