# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-23 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006__'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='custom_created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
